# Generated by Django 3.0.14 on 2023-03-22 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('crimsonboard', '0002_auto_20230317_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_number', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimsonboard.Courses')),
            ],
            options={
                'unique_together': {('id', 'course_id')},
            },
        ),
    ]
