# Generated by Django 3.0.14 on 2023-03-23 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crimsonboard', '0006_auto_20230323_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='user',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='course_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crimsonboard.Courses'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='enrollments',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(fields=('user', 'course_id'), name='unique_combined_model'),
        ),
    ]
