# Generated by Django 3.0.14 on 2023-03-24 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonboard', '0007_auto_20230323_0314'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollments',
            name='unique_combined_model',
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crimsonboard.userData'),
        ),
    ]
