# Generated by Django 3.0.14 on 2023-03-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonboard', '0008_auto_20230324_0114'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollments',
            unique_together={('user', 'course_id')},
        ),
    ]
